package/dtbocfg: bump to version 0.1.0
This bump will fix the following build failure with kernel >= 6.6 thanks
to
https://github.com/ikwzm/dtbocfg/commit/36e9dad7bdedc43b9c63aa48c3fc48ffc4d2b2dd:

/home/thomas/autobuild/instance-3/output-1/build/dtbocfg-0.0.9/./dtbocfg.c: In function ‘dtbocfg_overlay_item_create’:
/home/thomas/autobuild/instance-3/output-1/build/dtbocfg-0.0.9/./dtbocfg.c:68:19: error: too few arguments to function ‘of_overlay_fdt_apply’
   68 |         ret_val = of_overlay_fdt_apply(overlay->dtbo,overlay->dtbo_size, &ovcs_id);
      |                   ^~~~~~~~~~~~~~~~~~~~

https://github.com/ikwzm/dtbocfg/compare/v0.0.9...v0.1.0

Fixes:
 - http://autobuild.buildroot.org/results/e5bae7fa5558801c39f53a4a15ac550c3855322e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Acked-by: Herve Codina <herve.codina@bootlin.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>